version: 'x.x'
services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
  app:
    build: .
    restart: always
    ports:
      - "8081:8080"

  environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  depends_on:
      - db