version: 'x.x'
services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: corvosgordos
      POSTGRES_PASSWORD: 2000
      POSTGRES_DB: edusphere  # Nome do banco de dados a ser criado
    ports:
      - 3216:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U corvosgordos"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 3836:8080

  app:
    build: .
    restart: always
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/edusphere
      DB_USER: corvosgordos
      DB_PASSWORD: 2000
    depends_on:
      db:
        condition: service_healthy
